### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by takechihorn** [frandiox/vitesse-ssr-template#3]
Hi
I cloned latest version fixed at package.json. An error occurred when I build it. There wasn't any errors in previous version.Please tell me what did you wanna to change.
Should I use the previous version.
<img width="780" alt="スクリーンショット 2021-03-17 17 41 31" src="https://user-images.githubusercontent.com/49163199/111438795-04089b00-8748-11eb-8302-1c27b1e0d6e5.png">
Thank you!

**Comment by frandiox** [comment]
@takechihorn Seems related to ESBuild and Vite 2.1.0. I've changed the dep versions to use 2.0.x for now. Can you try again with that?

**Comment by takechihorn** [comment]
@frandiox 
Thank you for your updating!
It was Successful to run ! I'm going to develop a project using this template. 
Thanks a lot!

**Comment by frandiox** [comment]
@takechihorn I think it's been fixed in Vite `2.1.2`, in case you want to upgrade.
