### ISSUE TITLE
Error `No loader is configured for ".html" files: src/#foo/index.html`

### ISSUE THREAD

**Issue by yaquawa** [frandiox/vitesse-ssr-template#4]
Hi, I have a problem when a directory be prefixed with `#` and in that directory contains `.html` files.
To reproduce, make a directory called `#foo`, create a file `index.html` in that directory, run `pnpm dev`, then you got this:
```
Error `No loader is configured for ".html" files: src/#foo/index.html`
```

I've tried the original vite template, works fine, not sure why...

**Comment by frandiox** [comment]
@yaquawa I'm not even sure how Vite works with HTML files other than the root 🤔 
How are you importing and using that file in your project? Or are you just moving your root file to a subfolder?

**Comment by yaquawa** [comment]
> How are you importing and using that file in your project? Or are you just moving your root file to a subfolder?
I even didn't import it, if you removed the `#` prefix, it works... the directory be prefixed with `#` was generated by external libarary(amplify.js) and I can't change the name of it🤥

**Comment by frandiox** [comment]
@yaquawa I could reproduce it but it also happens with `pnpm dev:spa`, which is using pure Vite internally without SSR. Also, it happens in the original [`vitesse`](https://github.com/antfu/vitesse) template, which does not use `vite-ssr`.
Therefore, I think there's nothing we can do in this repo or even in `vite-ssr`.

The stack trace says it's `esbuild`, but it might be `vite` itself passing some configuration to the former. I've tried with the latest versions of these two dependencies, perhaps it actually worked in earlier versions, not sure 🤔

**Comment by yaquawa** [comment]
Thanks for reproducing! I could confirm that it also happens in the very original template(not the vitesse one) of vite.
strange.. I'm going to report this issue in the upstream repo.

**Comment by evilArsh** [comment]
that's because your whole dir include "#" ,just remove it and fixed ):

**Comment by ttareq** [comment]
> that's because your whole dir include "#" ,just remove it and fixed ):

 this helped me, thankyou

**Comment by inemtsev** [comment]
@yaquawa Did you ever find a fix for this? I am also using Amplify and it generates a strange directory with '#'

**Comment by yaquawa** [comment]
@inemtsev  I'm using Nuxt3 now.
